# FOI NECESSARIO INSTALAR A BIBLIOTECA PLAYSOUND E BAIXAR UM ARQUIVO MP3 PARA EXECUTAR #
import playsound  # IMPORTANTE O ARQUIVO MP3 DEVE ESTAR NO MESMO DIRETORIO DOS ARQUIVOS PYTHON #
playsound.playsound('teste.mp3')  # ENTRE PARENTESES ESTA O MESMO NOME DO ARQUIVO MP3 A SER EXECUTADO #
